### ISSUE TITLE
Precisa de copyright no mapa gerado

### ISSUE THREAD

**Issue by naoliv** [lpirola/mapa-daqui#13]
Também é necessário ter, pelo menos, “© OpenStreetMap contributors” no mapa (PDF) gerado pelo site.

http://www.openstreetmap.org/copyright

**Comment by nighto** [comment]
Acho que vale mais algo do tipo: "(C) Contribuidores do OpenStreetMap. Quer melhorar este mapa? Visite http://blabla" e ter um link no site do projeto explicando como fazer. Ou ainda linkando para http://www.openstreetmap.com.br/.

**Comment by naoliv** [comment]
@lpirola ficou quebrado entre duas páginas:
![Quebrado](http://i.imgur.com/AtBNPLV.png)
