### ISSUE TITLE
Problema com zoom e busca na hora de criar mapa

### ISSUE THREAD

**Issue by naoliv** [lpirola/mapa-daqui#14]
Aparentemente nem o zoom e nem a busca de http://mapadaqui.org/adotar-mapa funcionam

**Comment by nighto** [comment]
:+1: É, tentei usar aqui e não consegui.

**Comment by lpirola** [comment]
O zoom é travado devido ao estilo do mapa criado no mapbox que não dá suporte da forma que está feita hoje a mais níveis de zoom. Vou tentar esconder para não criar expectativa enquanto não resolvemos.

**Comment by nighto** [comment]
Retirou-se o controle de zoom do mapa, mas a busca continua não funcionando. Abro outra issue?

**Comment by lpirola** [comment]
Valeu por reportar os bugs @nighto! o/
