### ISSUE TITLE
Abrir PDF gerado em uma aba atrás da aba ativa

### ISSUE THREAD

**Issue by lucasnantonio** [lpirola/mapa-daqui#5]
Para não atrapalhar o preenchimento do email. É possível?

**Comment by lpirola** [comment]
@lucasnantonio não é muito possível não :/ Procurei e só apareceu algumas formas um pouco gambiarradas de fazer e que dependendo do browser, não funciona.

Será que conseguimos pensar em outra forma de resolver?

**Comment by lucasnantonio** [comment]
hmmm certo, será que dá pra fazer aquele download de arquivo que não abre abas, mas salva em algum lugar?

**Comment by lucasnantonio** [comment]
Uma outra solução pra não cortar a digitação da pessoa é só liberar o download depois do preenchimento do email. Nesse caso, teríamos que add um botão "Pular cadastro" que libera também...que acha?

**Comment by lpirola** [comment]
consegui resolver deixando o download acontecer no background, salvando no computador direto. o/

**Comment by lucasnantonio** [comment]
\o/ tu é o mestre
